name: sync overleaf projects
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  syncprojects:
    runs-on: ubuntu-latest
    steps:
      - name: overleaf-sync
        uses: jmir1/overleaf-sync@0.0.1
        with:
          email: ${{ SECRETS.INPUT_EMAIL }}
          password: ${{ SECRETS.INPUT_PASSWORD }}
          repotoken: ${{ SECRETS.GITHUB_TOKEN }}
          gituser: ${{ github.actor }}
          reponame: ${{ github.repository }}
          gitemail: "${{ github.actor }}@users.noreply.github.com"
