name: Manual Overleaf Sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Overleaf Sync
        uses: mathisve/overleaf-sync-action@main
        with:
          OVERLEAF_PROJECT_ID: ${{ secrets.OVERLEAF_PROJECT_ID }}
          OVERLEAF_COOKIE: ${{ secrets.OVERLEAF_COOKIE }}
